version: "3"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - .gosql-db-persisted:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build: .
    environment:
      GIN_MODE: "release"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:${API_PORT}"
    command: go run main.go
    links:
      - db
