version: "2"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - .gomvc-db-persisted:/var/lib/mysql
